// File generated by FlutterFire CLI / Development fallback.
// Project ID: uninotes-ai-89d4a

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSy-uninotes-ai-89d4a-web-key',
    appId: '1:112990226265928750048:web:89d4a00000000000',
    messagingSenderId: '112990226265928750048',
    projectId: 'uninotes-ai-89d4a',
    authDomain: 'uninotes-ai-89d4a.firebaseapp.com',
    storageBucket: 'uninotes-ai-89d4a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSy-uninotes-ai-89d4a-android-key',
    appId: '1:112990226265928750048:android:89d4a00000000000',
    messagingSenderId: '112990226265928750048',
    projectId: 'uninotes-ai-89d4a',
    storageBucket: 'uninotes-ai-89d4a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSy-uninotes-ai-89d4a-ios-key',
    appId: '1:112990226265928750048:ios:89d4a00000000000',
    messagingSenderId: '112990226265928750048',
    projectId: 'uninotes-ai-89d4a',
    storageBucket: 'uninotes-ai-89d4a.appspot.com',
    iosBundleId: 'com.uninotesai.uninotesAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSy-uninotes-ai-89d4a-macos-key',
    appId: '1:112990226265928750048:ios:89d4a00000000000',
    messagingSenderId: '112990226265928750048',
    projectId: 'uninotes-ai-89d4a',
    storageBucket: 'uninotes-ai-89d4a.appspot.com',
    iosBundleId: 'com.uninotesai.uninotesAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSy-uninotes-ai-89d4a-win-key',
    appId: '1:112990226265928750048:web:89d4a00000000000',
    messagingSenderId: '112990226265928750048',
    projectId: 'uninotes-ai-89d4a',
    authDomain: 'uninotes-ai-89d4a.firebaseapp.com',
    storageBucket: 'uninotes-ai-89d4a.appspot.com',
  );
}
