// File generated by FlutterFire CLI / Development fallback.
// Ignore errors on null safety or target platforms.
// Replace with your real Firebase config via `flutterfire configure`.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSy-DEV-DUMMY-KEY-WEB',
    appId: '1:000000000000:web:0000000000000000000000',
    messagingSenderId: '000000000000',
    projectId: 'uninotes-ai-dev',
    authDomain: 'uninotes-ai-dev.firebaseapp.com',
    storageBucket: 'uninotes-ai-dev.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSy-DEV-DUMMY-KEY-ANDROID',
    appId: '1:000000000000:android:0000000000000000000000',
    messagingSenderId: '000000000000',
    projectId: 'uninotes-ai-dev',
    storageBucket: 'uninotes-ai-dev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSy-DEV-DUMMY-KEY-IOS',
    appId: '1:000000000000:ios:0000000000000000000000',
    messagingSenderId: '000000000000',
    projectId: 'uninotes-ai-dev',
    storageBucket: 'uninotes-ai-dev.appspot.com',
    iosBundleId: 'com.uninotesai.uninotesAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSy-DEV-DUMMY-KEY-MACOS',
    appId: '1:000000000000:ios:0000000000000000000000',
    messagingSenderId: '000000000000',
    projectId: 'uninotes-ai-dev',
    storageBucket: 'uninotes-ai-dev.appspot.com',
    iosBundleId: 'com.uninotesai.uninotesAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSy-DEV-DUMMY-KEY-WIN',
    appId: '1:000000000000:web:0000000000000000000000',
    messagingSenderId: '000000000000',
    projectId: 'uninotes-ai-dev',
    authDomain: 'uninotes-ai-dev.firebaseapp.com',
    storageBucket: 'uninotes-ai-dev.appspot.com',
  );
}
